version: '2'
services:
    deccom-app:
        image: deccom
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://deccom-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=deccom
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    deccom-mongodb:
        extends:
            file: mongodb.yml
            service: deccom-mongodb
